# Generated by Django 3.2.7 on 2021-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='kcal',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_fl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugars',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
