# Generated by Django 3.2.7 on 2021-09-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210911_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='n',
            field=models.ManyToManyField(through='products.Allergy_Product', to='products.Product'),
        ),
    ]
