# Generated by Django 3.2.7 on 2021-09-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allergy_n'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy_product',
            table='allergy_products',
        ),
    ]
